version: '3.1'

services:
  php-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    tty: true

